#!/usr/bin/env python3
"""Generates a small corpus of synthetic test programs for M6's FS-UAE
test matrix (PROJECT_PLAN.md M6 - run_corpus_test.sh runs every backend
against every one of these).

tests/uae/e2e/program.s and e2e_large/gen_large_program.py each probe
one shape of input (a couple of relocations; several KB of prose with
22 relocations and a small BSS). Real Amiga executables vary along
axes neither of those alone exercises - this corpus adds the ones that
matter most to a packer's own logic, one item per axis, each kept
short (a handful of serial lines, not several KB) to keep the boot
matrix's wall-clock cost down since every item runs under every
backend:

  no_relocs    - zero relocation sites at all (FLAG_HAS_RELOCS clear -
                 never exercised by the two existing e2e programs,
                 which both have at least one reloc).
  chip_mem     - a hunk explicitly marked Chip RAM (vasm/vlink's
                 `_c` section suffix), forcing the packed program's
                 single resident block into Chip RAM at runtime -
                 never exercised on real hardware before this: the
                 MEMF_CHIP path in stubs/common/runtime.i only had a
                 host-side unit test (container.zig) checking the
                 header *flag* gets set, not that AllocMem'ing Chip
                 RAM and running from it actually works.
  bss_heavy    - a large (64K) BSS relative to a tiny code/data
                 region, and - unlike every earlier e2e program, which
                 declares BSS but never reads it back - actually reads
                 a spread of BSS bytes at runtime and reports whether
                 they came back zero, verifying AllocMem's MEMF_CLEAR
                 actually zeroed a nontrivial region rather than just
                 sizing it correctly.
  incompressible - a payload that doesn't compress (a deterministic
                 non-repeating byte sequence, not real randomness -
                 reproducible across runs), the worst case for every
                 LZ-family backend and a real edge case: does the
                 pack/depack pipeline stay correct when compression
                 doesn't help, or even hurts?

Each item writes a `<name>.s` (fed to vasm -Fhunk, then vlink) and a
`<name>.expected` (the exact bytes the packed, booted program must
write to the serial port) into the given output directory, from the
same in-script data, so source and expectation can never drift apart -
same discipline as gen_large_program.py's own two-file output.

Usage: gen_corpus.py <out_dir>
"""
import sys
import os

SENTINEL_PREFIX = "EXECRAM-CORPUS"

# Shared serial-port bit-banging preamble/helpers, identical across
# every item (lifted from tests/uae/e2e/program.s) - kept as one
# constant rather than re-typed per item so all corpus items pace
# identically and any future baud-rate change only needs one edit.
PREAMBLE = """\
\tmove.w\t#$7fff,$dff09a\t; INTENA: quiet down interrupts
\tmove.w\t#$7fff,$dff09c\t; INTREQ: clear pending
\tmove.w\t#368,$dff032\t; SERPER: ~9600 baud, PAL
"""

SEND_HELPERS = """\
; Sends the null-terminated string at A0 over the serial port.
sendmsg:
.next:
\tmove.b\t(a0)+,d0
\tbeq.s\t.done
\tbsr.s\tsendchar
\tbra.s\t.next
.done:
\trts

sendchar:
\tor.w\t#$100,d0
\tmove.w\td0,$dff030
\tmove.l\t#3000,d1
.delay:
\tsubq.l\t#1,d1
\tbne.s\t.delay
\trts
"""


def item_no_relocs():
    """Single CODE hunk, nothing else - no DATA/BSS hunk exists at all,
    so there is nothing to relocate (flatten.zig's reloc_stream is just
    the 0xFE terminator; container.zig's FLAG_HAS_RELOCS stays clear)."""
    sentinel = f"{SENTINEL_PREFIX}-NORELOCS-OK"
    src = f"""\
; Corpus item "no_relocs" - generated by gen_corpus.py, do not edit by
; hand. A single CODE hunk with no DATA or BSS hunk at all: the string
; below is reached via a plain PC-relative `lea`, so there is nothing
; for any relocation to patch. See gen_corpus.py's own module doc.

\tsection\tCODE,code
start:
{PREAMBLE}
\tlea\tmsg(pc),a0
\tbsr.w\tsendmsg
.hang:
\tbra.s\t.hang

{SEND_HELPERS}
msg:
\tdc.b\t'{sentinel}',10,0
\teven
"""
    return src, (sentinel + "\n").encode("ascii")


def item_chip_mem():
    """A DATA hunk explicitly marked Chip RAM (vasm's `_c` section
    suffix) holding the message, reached via an absolute long load -
    both forces the whole packed program into Chip RAM at runtime
    (flatten.zig's mem_chip auto-detection) and exercises a real
    CODE->DATA relocation at the same time."""
    sentinel = f"{SENTINEL_PREFIX}-CHIPMEM-OK"
    src = f"""\
; Corpus item "chip_mem" - generated by gen_corpus.py, do not edit by
; hand. msg lives in a hunk explicitly marked Chip RAM (the `_c`
; section suffix) - forces the packed program's whole resident block
; into Chip RAM at runtime (docs/format-spec.md's all-or-nothing
; Chip/Fast choice), not just Fast/Any RAM like every other corpus
; item. Reached via `move.l #msg,a0` (absolute, not PC-relative), so
; this also exercises a real CODE->DATA relocation. See gen_corpus.py's
; own module doc.

\tsection\tCODE,code
start:
{PREAMBLE}
\tmove.l\t#msg,a0\t; absolute: a CODE->DATA reloc
\tbsr.w\tsendmsg
.hang:
\tbra.s\t.hang

{SEND_HELPERS}
\tsection\tDATA,data_c
msg:
\tdc.b\t'{sentinel}',10,0
\teven
"""
    return src, (sentinel + "\n").encode("ascii")


def item_bss_heavy():
    """A 64K BSS behind a tiny code/data region - and unlike every
    earlier e2e program, actually reads a spread of BSS bytes back at
    runtime and reports whether AllocMem's MEMF_CLEAR really zeroed
    them, not just declaring the space and trusting it. `lea big_bss,a0`
    (no `(pc)`) assembles as absolute, not PC-relative, so this also
    exercises a real CODE->BSS relocation - a target kind none of the
    other corpus items or the two earlier e2e programs happen to use
    (those relocate onto CODE/DATA, never BSS)."""
    sentinel_ok = f"{SENTINEL_PREFIX}-BSSHEAVY-ZERO-OK"
    sentinel_fail = f"{SENTINEL_PREFIX}-BSSHEAVY-ZERO-FAIL"
    bss_size = 65536
    check_stride = 4096  # sample every 4K across the whole 64K region
    src = f"""\
; Corpus item "bss_heavy" - generated by gen_corpus.py, do not edit by
; hand. A {bss_size}-byte BSS behind a tiny code/data region - large
; enough that a MEMF_CLEAR bug (or a stub that got the BSS size wrong)
; has real room to show up. Unlike every earlier e2e program, this one
; actually samples BSS bytes at runtime (every {check_stride} bytes)
; and ORs them together, reporting ZERO-OK only if every sampled byte
; really came back zero - not just that the packed size accounted for
; it. See gen_corpus.py's own module doc.

\tsection\tCODE,code
start:
{PREAMBLE}
\tlea\tbig_bss,a0
\tmove.l\t#{bss_size // check_stride},d7
\tmoveq\t#0,d6
.checkloop:
\tor.b\t(a0),d6
\tadda.l\t#{check_stride},a0
\tsubq.l\t#1,d7
\tbne.s\t.checkloop

\ttst.b\td6
\tbeq.s\t.zero_ok
\tlea\tmsg_fail(pc),a0
\tbsr.w\tsendmsg
\tbra.s\t.hang
.zero_ok:
\tlea\tmsg_ok(pc),a0
\tbsr.w\tsendmsg
.hang:
\tbra.s\t.hang

{SEND_HELPERS}
msg_ok:
\tdc.b\t'{sentinel_ok}',10,0
\teven
msg_fail:
\tdc.b\t'{sentinel_fail}',10,0
\teven

\tsection\tBSS,bss
big_bss:
\tds.b\t{bss_size}
"""
    return src, (sentinel_ok + "\n").encode("ascii")


def item_incompressible():
    """A deterministic (reproducible, not real randomness), non-
    repeating byte sequence as payload - the worst case for every
    LZ-family backend, and a real edge case for auto-mode backend
    selection (does compression ever make things *worse*, and if so
    does execram still produce a correct, just larger, output?)."""
    sentinel = f"{SENTINEL_PREFIX}-INCOMPRESSIBLE-OK"
    # A small, fast, deterministic non-repeating generator (an LCG) -
    # not cryptographic and not claiming real entropy, just enough
    # byte-to-byte unpredictability that LZ77-family matchers find
    # essentially no reusable matches, which is what this item needs
    # to test, and 100% reproducible run to run (no os.urandom).
    state = 12345
    payload = bytearray()
    for _ in range(2000):
        state = (1103515245 * state + 12345) & 0x7FFFFFFF
        payload.append(state & 0xFF)
    hex_bytes = ",".join(f"${b:02x}" for b in payload)
    # dc.b lines: keep them from growing unreasonably long for vasm.
    lines = [hex_bytes[i : i + 200] for i in range(0, len(hex_bytes), 200)]
    dc_lines = "\n".join(f"\tdc.b\t{line.strip(',')}" for line in lines)
    src = f"""\
; Corpus item "incompressible" - generated by gen_corpus.py, do not
; edit by hand. `blob` is a deterministic (reproducible, not real
; randomness - an LCG, not os.urandom) {len(payload)}-byte sequence
; with no repeated runs for any LZ matcher to find - the worst case
; for every LZ-family backend, verifying the pipeline stays correct
; (not just that it happens to shrink things) when compression doesn't
; help. Sent back over serial and diffed byte-for-byte against the
; source bytes, same rigor as the sentinel-string items even though
; this data isn't printable text. See gen_corpus.py's own module doc.

\tsection\tCODE,code
start:
{PREAMBLE}
\tlea\tblob(pc),a0
\tmove.l\t#{len(payload) - 1},d7
.next:
\tmove.b\t(a0)+,d0
\tbsr.s\tsendchar
\tdbf\td7,.next

\tlea\tmsg(pc),a0
\tbsr.w\tsendmsg
.hang:
\tbra.s\t.hang

{SEND_HELPERS}
msg:
\tdc.b\t'{sentinel}',10,0
\teven
blob:
{dc_lines}
\teven
"""
    return src, bytes(payload) + (sentinel + "\n").encode("ascii")


ITEMS = {
    "no_relocs": item_no_relocs,
    "chip_mem": item_chip_mem,
    "bss_heavy": item_bss_heavy,
    "incompressible": item_incompressible,
}


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2
    out_dir = sys.argv[1]
    os.makedirs(out_dir, exist_ok=True)

    for name, builder in ITEMS.items():
        src, expected = builder()
        with open(os.path.join(out_dir, f"{name}.s"), "w") as f:
            f.write(src)
        with open(os.path.join(out_dir, f"{name}.expected"), "wb") as f:
            f.write(expected)
        print(f"wrote {name}.s and {name}.expected ({len(expected)} expected bytes)")

    return 0


if __name__ == "__main__":
    sys.exit(main())
